### ISSUE TITLE
cant proxy homepage

### ISSUE THREAD

**Issue by jeffpreussner** [djpogo/vite-js-proxy#1]
Using this code to create a proxy dev server to develop and debug production code locally. I am able to get it up and running with some minor tweaks but I cant seem to get HMR working on homepage is it does on other pages.

my proxy config:

```
{
	"target": "http://example.com",
	"proxyPath": "/proxy/",
	"addBaseTag": true,
	"proxyRewriteSelector": ["[src^='/']","[href^='/']"],
	"proxyIgnoreTags": [],
	"proxyRoutes": [
		{
			"path": "/api/"
		},
		{
			"path": "/sites/"
		},
		{
			"path": "/modules/"
		},
		{
			"path": "/themes/"
		}
	]
}
```

This code works on "http://localhost:3000/search" great but when I hit "http://localhost:3000" i see the index.html with no proxied code and message in the console from loadpage.js _"/ looks like a user custom proxy route and is not markup tunneled"_, if i add `{"path": "/"}` to proxyRoutes it redirects to the homepage outside of vite app.

Am I configured correctly?

**Comment by jeffpreussner** [comment]
Update: removing the check for existing route allows for access to homepage.
```pRoutes.find(route => route?.path.indexOf(pathname) === 0)```

**Comment by djpogo** [comment]
~~Hey @jeffpreussner can you provide a PR for that?~~

I see - I change the check of custom routes to be an exact match. Let me know if this works for you.

And I update the project to latest vite.
